---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: three-tier-app
data:
  VITE_API_URL: "http://backend.santosh.website"  # Update to your actual frontend API URL
  MONGO_URI: "mongodb://mongodb:27017/employees"  
  # MONGO_URI: "mongodb://mongodb-0.mongodb.three-tier-app.svc.cluster.local:27017,mongodb-1.mongodb.three-tier-app.svc.cluster.local:27017,mongodb-2.mongodb.three-tier-app.svc.cluster.local:27017/employees?replicaSet=rs0"

# the above MONGO_URI is for a replica set with 3 pods when u r using statefulset with multiple replicas


  # mongodb://mongodb.three-tier-app.svc.cluster.local:27017/?replicaSet=rs0
  # <pod-name>.<service-name>.<namespace>.svc.cluster.local
  # mongodb://mongodb:27017/?replicaSet=rs0

