apiVersion: v1
kind: ServiceAccount
metadata:
  name: three-tier-app
  namespace: three-tier-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: three-tier-app
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: three-tier-app
subjects:
- kind: ServiceAccount
  name: three-tier-app
  namespace: three-tier-app
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io